apiVersion: v1
kind: Service
metadata:
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
  labels:
    k8s-app: claim-ms
  name: claim-ms
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: "tcp-9092"
      port: 9092
      protocol: TCP
      targetPort: 9092
      nodePort: 30128
  selector:
    k8s-app: claim-ms
  sessionAffinity: None
  type: NodePort
