apiVersion: v1
kind: Service
metadata:
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
  labels:
    k8s-app: registry
  name: registry
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: "tcp-9091"
      port: 9091
      protocol: TCP
      targetPort: 9091
      nodePort: 30127
  selector:
    k8s-app: registry
  sessionAffinity: None
  type: NodePort
